name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hey! Looks like this is your first time opening an issue, please make sure you're familiar with the [contribution guidelines](https://github.com/ufosc/Club_Website_2/blob/main/CONTRIBUTING.md). Thanks for contributing to the UF Open Source Club."
          pr-message: "Hey! Looks like this is your first time opening a PR, please make sure you're familiar with the [contribution guidelines](https://github.com/ufosc/Club_Website_2/blob/main/CONTRIBUTING.md). Thanks for contributing to the UF Open Source Club."
